version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qrp26wsje4sn"
s3_prefix = "firstlambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
