AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable
Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
#  ReadOrdersFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: ordersapi
#      Handler: ordersapi.ReadOrdersLambda::getOrders
#      Policies:
#        - DynamoDBReadPolicy:
#            TableName: !Ref OrdersTable
#      Events:
#        OrderEvents:
#          Type: Api
#          Properties:
#            Path: /orders
#            Method: GET